#!/usr/bin/env python
"""Print the current training baseline and candidate speed tests."""


def main() -> None:
    print("=" * 70)
    print("PhaseWindowTCN 训练加速检查清单")
    print("=" * 70)
    print()
    print("目标服务器:")
    print("  - GPU: NVIDIA RTX5880, 48 GiB")
    print("  - CPU: AMD vCPU, 32 核")
    print("  - 内存: 64 GB")
    print()
    print("当前正式基线:")
    print("  - batch_size: 16")
    print("  - num_workers: 2")
    print("  - persistent_workers: false")
    print("  - lr: 0.00015")
    print("  - epochs: 80")
    print("  - early_stopping.patience: 10")
    print("  - amp: float16")
    print("  - tf32/cudnn_benchmark: true")
    print()
    print("1. 先跑当前基线")
    print("   PYTHONPATH=src python -m pipeline.run_experiment \\")
    print("     --config configs/experiment/phase_window_tcn_ablation/phase_window_tcn_ablation.json \\")
    print("     --dataset-dir data/wv4-formal-hitran-standard-6000 \\")
    print("     --output-root outputs")
    print()
    print("2. 记录指标")
    print("   - epoch_seconds")
    print("   - train_samples_per_second")
    print("   - gpu_memory_allocated_mb / gpu_memory_reserved_mb")
    print("   - val_loss")
    print("   - test/extrapolation x_N2 R2")
    print()
    print("3. 再按顺序测试候选")
    print("   - num_workers: 0/2/4/8")
    print("   - torch.compile: reduce-overhead, 单 run")
    print("   - batch_size: 20 -> 24 -> 32")
    print()
    print("详细方案: docs/训练配置优化方案.md")
    print("=" * 70)


if __name__ == "__main__":
    main()
