"""Print the current PhaseWindowTCN training baseline and candidate sweeps."""


def compare_configs() -> None:
    print("=" * 80)
    print("PhaseWindowTCN 训练配置：当前基线与候选加速")
    print("=" * 80)
    print()
    print("目标服务器:")
    print("  GPU: NVIDIA RTX5880, 48 GiB")
    print("  CPU: AMD vCPU, 32 核")
    print("  RAM: 64 GB")
    print()
    print("当前正式基线:")
    print("  batch_size: 16")
    print("  num_workers: 2")
    print("  persistent_workers: false")
    print("  lr: 0.00015")
    print("  epochs: 80")
    print("  early_stopping.patience: 10")
    print("  amp: enabled, float16")
    print("  performance: tf32=true, cudnn_benchmark=true, compile=false")
    print()
    print("候选实测顺序:")
    print("  1. 记录当前基线 epoch_seconds / samples/s / 显存 / N2 R2")
    print("  2. worker sweep: num_workers=0/2/4/8")
    print("  3. 单 run 测 torch.compile(mode='reduce-overhead')")
    print("  4. batch sweep: 20 -> 24 -> 32")
    print()
    print("注意:")
    print("  batch=32 在旧 24 GiB 环境 OOM；48 GiB 服务器可重测，但不能直接转正。")
    print("  只有速度、显存、val_loss、test/extrapolation x_N2 R2 全部通过，才更新正式配置。")
    print()
    print("运行当前基线:")
    print("PYTHONPATH=src python -m pipeline.run_experiment \\")
    print("  --config configs/experiment/phase_window_tcn_ablation/phase_window_tcn_ablation.json \\")
    print("  --dataset-dir data/wv4-formal-hitran-standard-6000 \\")
    print("  --output-root outputs")
    print()
    print("详细方案: docs/训练配置优化方案.md")
    print("=" * 80)


if __name__ == "__main__":
    compare_configs()
