"""Ar-He-CO2 数据生成、物理模型、打包和质量检查。"""

from gf.sim.ar_he_co2 import PilotCondition, PilotRecord, build_pilot_record
from gf.sim.a1_dataset import (
    A1Condition,
    A1Dataset,
    A1PhysicsConfig,
    DEFAULT_A1_PHYSICS,
    assign_a1_splits,
    deterministic_signal_vector,
    generate_a1_conditions,
    generate_dataset,
    load_dataset,
)
from gf.sim.a2m_dataset import (
    A2M_AXES,
    A2M_DATA_VERSION_PREFIX,
    A2MObservation,
    A2MDataset,
    A2M_PRIMARY_AXES,
    A2M_SCHEMA_VERSION,
    A2MTestLockError,
    compute_a2m_split_hash,
    generate_a2m_formal_holdout,
    load_a2m_dataset,
    validate_a2m_data_config,
)
from gf.sim.a2h_dataset import (
    A2HCondition,
    A2HDataset,
    A2HObservation,
    A2HPhysicsConfig,
    CalibrationProfile,
    NoiseProfile,
    composition_region,
    compute_split_family_hash,
    deterministic_a2h_signal_vector,
    generate_a2h_dataset,
    load_a2h_dataset,
    nominal_signal_parity,
)

__all__ = [
    "A1Condition",
    "A1Dataset",
    "A1PhysicsConfig",
    "A2M_AXES",
    "A2M_DATA_VERSION_PREFIX",
    "A2MObservation",
    "A2MDataset",
    "A2M_PRIMARY_AXES",
    "A2M_SCHEMA_VERSION",
    "A2MTestLockError",
    "compute_a2m_split_hash",
    "generate_a2m_formal_holdout",
    "load_a2m_dataset",
    "validate_a2m_data_config",
    "DEFAULT_A1_PHYSICS",
    "PilotCondition",
    "PilotRecord",
    "assign_a1_splits",
    "build_pilot_record",
    "deterministic_signal_vector",
    "generate_a1_conditions",
    "generate_dataset",
    "load_dataset",
    "A2HCondition",
    "A2HDataset",
    "A2HObservation",
    "A2HPhysicsConfig",
    "CalibrationProfile",
    "NoiseProfile",
    "composition_region",
    "compute_split_family_hash",
    "deterministic_a2h_signal_vector",
    "generate_a2h_dataset",
    "load_a2h_dataset",
    "nominal_signal_parity",
]
