from sg.sim.generation.spectral.cache import SpectralCacheKey, cache_path, read_cached_spectrum, write_cached_spectrum
from sg.sim.generation.spectral.defaults import (
    DEFAULT_HITRAN_GAS_SPECS,
    DEFAULT_HITRAN_GRID_SPECS,
    DEFAULT_NDIR_FILTERS,
    SPECTRAL_DEFAULTS_CONFIG_PATH,
    SPECTRAL_DEFAULTS_PAYLOAD,
    SYNGAS_CHANNEL_GAS_SPECS,
    SYNGAS_HITRAN_GAS_SPECS_BY_NAME,
    SYNGAS_HITRAN_GRID_SPECS,
    SYNGAS_NDIR_FILTERS,
    get_default_hitran_grid,
    get_default_ndir_filter,
    get_syngas_channel_gas_specs,
    get_syngas_hitran_grid,
    get_syngas_ndir_filter,
)
from sg.sim.generation.spectral.filters import NDIRFilter, gaussian_filter
from sg.sim.generation.spectral.hitran_backend import (
    BOLTZMANN_J_PER_K,
    HITRAN_ABSORPTION_BACKEND,
    STANDARD_ATMOSPHERE_PA,
    HitranGasSpec,
    HitranGridSpec,
    MissingHitranCacheError,
    MissingHitranTableError,
    compute_hitran_ndir_absorbance,
    convert_hitran_coeff_to_per_percent_m,
    hitran_cache_key,
)
from sg.sim.generation.spectral.integration import integrate_channel_absorbance
from sg.sim.generation.spectral.quantitative_table import (
    QUANTITATIVE_TABLE_BACKEND,
    SUPPORTED_QUANTITATIVE_UNITS,
    convert_quantitative_coeff_to_per_percent_m,
    load_quantitative_spectrum_csv,
    resample_spectrum_to_grid,
)
from sg.sim.generation.spectral.tabulated_backend import (
    PreparedTabulatedSpectra,
    TabulatedSpectrum,
    compute_prepared_tabulated_ndir_absorbance,
    compute_tabulated_ndir_absorbance,
    prepare_tabulated_spectra,
)

__all__ = [
    "BOLTZMANN_J_PER_K",
    "DEFAULT_HITRAN_GAS_SPECS",
    "DEFAULT_HITRAN_GRID_SPECS",
    "DEFAULT_NDIR_FILTERS",
    "HITRAN_ABSORPTION_BACKEND",
    "HitranGasSpec",
    "HitranGridSpec",
    "MissingHitranCacheError",
    "MissingHitranTableError",
    "NDIRFilter",
    "PreparedTabulatedSpectra",
    "QUANTITATIVE_TABLE_BACKEND",
    "SPECTRAL_DEFAULTS_CONFIG_PATH",
    "SPECTRAL_DEFAULTS_PAYLOAD",
    "SYNGAS_CHANNEL_GAS_SPECS",
    "SYNGAS_HITRAN_GAS_SPECS_BY_NAME",
    "SYNGAS_HITRAN_GRID_SPECS",
    "SYNGAS_NDIR_FILTERS",
    "SpectralCacheKey",
    "STANDARD_ATMOSPHERE_PA",
    "SUPPORTED_QUANTITATIVE_UNITS",
    "TabulatedSpectrum",
    "cache_path",
    "compute_hitran_ndir_absorbance",
    "compute_prepared_tabulated_ndir_absorbance",
    "compute_tabulated_ndir_absorbance",
    "convert_hitran_coeff_to_per_percent_m",
    "convert_quantitative_coeff_to_per_percent_m",
    "gaussian_filter",
    "get_default_hitran_grid",
    "get_default_ndir_filter",
    "get_syngas_channel_gas_specs",
    "get_syngas_hitran_grid",
    "get_syngas_ndir_filter",
    "hitran_cache_key",
    "integrate_channel_absorbance",
    "load_quantitative_spectrum_csv",
    "prepare_tabulated_spectra",
    "read_cached_spectrum",
    "resample_spectrum_to_grid",
    "write_cached_spectrum",
]
